"""The page shell every server-rendered page shares (sign-in, first run, Settings).
Self-contained documents, no build step, no CDN."""
from __future__ import annotations

from .. import themes
from ..ais import CSS as AI_CSS
from ..brand import logo
from ..render import WS_MENU_CSS

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<meta name="robots" content="noindex,nofollow">
<title>{title} &middot; Dexio</title>
<link rel="icon" href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii03NjkgLTg1MiAxNTY3IDE1NjciPjwhLS0gRGV4aW8gbWFyazogYSBzbWFsbCBncmFwaCwgaHViIGFuZCBmb3VyIG5vZGVzLiBCdWlsdCBieSBicmFuZC9idWlsZC5weS4gLS0+PHJlY3QgeD0iLTc2OSIgeT0iLTg1MiIgd2lkdGg9IjE1NjciIGhlaWdodD0iMTU2NyIgcng9IjM0NSIgZmlsbD0iIzAwMDAwMCIvPjxwYXRoIGQ9Ik03OS45IDAuMEwyMC40IC00NzUuMkwtMjAuNCAtNDc1LjJMLTc5LjkgMC4wWk0yOS4xIDc0LjRMNDk4LjEgLTE3My4yTDQ4My4zIC0yMTEuMkwtMjkuMSAtNzQuNFpNLTUyLjMgNjAuM0wzOTIuNCAzNjcuNEw0MTkuMCAzMzYuNkw1Mi4zIC02MC4zWk0tMzMuNiAtNzIuNUwtNDYyLjIgMTkxLjhMLTQ0NS4wIDIyOC44TDMzLjYgNzIuNVoiIGZpbGw9IiNmZmZmZmYiLz48Y2lyY2xlIGN4PSIwLjAiIGN5PSItNDc1LjIiIHI9Ijg3LjYiIGZpbGw9IiNmZmZmZmYiLz48Y2lyY2xlIGN4PSI0OTAuNyIgY3k9Ii0xOTIuMiIgcj0iODcuNiIgZmlsbD0iI2ZmZmZmZiIvPjxjaXJjbGUgY3g9IjQwNS43IiBjeT0iMzUyLjAiIHI9Ijc0LjUiIGZpbGw9IiNmZmZmZmYiLz48Y2lyY2xlIGN4PSItNDUzLjYiIGN5PSIyMTAuMyIgcj0iOTYuNCIgZmlsbD0iI2ZmZmZmZiIvPjxjaXJjbGUgY3g9IjAuMCIgY3k9IjAuMCIgcj0iMTY2LjUiIGZpbGw9IiMzOGJkZjgiLz48L3N2Zz4=">
__THEME_HEAD__
<style>
  /* colours: every mode and theme, generated by dexio/themes.py */
  __THEME_CSS__

  * {{ box-sizing:border-box; }}
  body {{
    margin:0; min-height:100dvh; display:grid; place-items:center;
    padding:24px 16px max(24px,env(safe-area-inset-bottom));
    /* the page takes a tint of the theme's header colour; none in the default */
    background:color-mix(in srgb,var(--chrome) 8%,var(--sunken)); color:var(--text);
    --line:var(--line-strong);  /* these pages draw every border one step firmer */
    font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;
    -webkit-text-size-adjust:100%;
  }}
  .card {{ width:100%; max-width:{width}px; }}
  .top {{ display:flex; align-items:center; gap:.6rem; margin-bottom:1.5rem; }}
  .logo {{ display:flex; align-items:center; gap:8px; color:var(--text); margin-bottom:.3rem; }}
  .logo svg {{ display:block; flex:none; }}
  .top b {{ font-size:1.05rem; font-weight:600; letter-spacing:-.01em; }}
  .top span {{ color:var(--muted); font-size:.85rem; }}
  .top .sp {{ flex:1; }}

  form {{ background:var(--panel); border:1px solid var(--line);
         border-radius:10px; padding:1.5rem; }}
  label {{ display:block; font-size:.78rem; text-transform:uppercase;
          letter-spacing:.06em; color:var(--muted); margin-bottom:.35rem; }}
  input {{
    width:100%; padding:.65rem .7rem; margin-bottom:1rem; min-height:44px;
    background:var(--field); color:var(--text);
    border:1px solid var(--line); border-radius:6px;
    font-size:16px;  /* 16px or iOS Safari zooms the page on focus */
  }}
  input:focus {{ outline:none; border-color:var(--accent);
                box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 22%,transparent); }}
  /* ---- buttons: one system for the app and the site (Forrest, 2026-09-28, option A of
     four). Three sizes: 44px (sign-in, a button beside a 44px input, a step's main
     action), 38px (settings forms, plan cards, the connect steps' Back and Next) and 32px
     (row actions, copy, the pager, Sign out). 8px corners. Primary darkens on hover and
     further when pressed. Outline buttons take a faint fill and a firmer border, never
     red; danger is an outline that turns solid red on hover. A 2px accent ring on
     keyboard focus, half opacity when disabled, and the page's font. They were five
     heights with 6px corners here and 8px on the site, four different hovers (Sign out
     went red), and no pressed, focus or disabled look. Colours: themes.py. */
  button {{ font-family:inherit; }}
  button[type=submit], a.button, a.cta, button.cta, button.copy, .social, button.quiet,
    button.danger {{ transition:background-color .12s ease,border-color .12s ease,color .12s ease; }}
  button[type=submit] {{
    width:100%; min-height:44px; border:1px solid transparent; border-radius:8px;
    background:var(--btn); color:var(--btn-text); font-size:15px; font-weight:600;
    cursor:pointer;
  }}
  button[type=submit]:hover {{ background:var(--btn-hover); }}
  button[type=submit]:active {{ background:var(--btn-press); }}
  button:focus-visible, a.button:focus-visible, a.cta:focus-visible, .social:focus-visible {{
    outline:2px solid var(--accent); outline-offset:2px; }}
  button:disabled {{ opacity:.5; cursor:default; pointer-events:none; }}
  .error {{ background:var(--bad-bg); border:1px solid var(--bad-line);
           color:var(--bad-text); border-radius:6px; padding:.55rem .7rem;
           margin-bottom:1rem; font-size:.88rem; }}
  .foot {{ margin-top:1rem; text-align:center; color:var(--muted); font-size:.78rem; }}
  .social {{ display:flex; align-items:center; justify-content:center; gap:.6rem;
            width:100%; min-height:44px; margin-bottom:.6rem; border:1px solid var(--btn-line);
            border-radius:8px; background:var(--panel); color:var(--text);
            font-size:15px; font-weight:600; text-decoration:none; }}
  .social:hover {{ background:var(--btn-fill-hover); border-color:var(--btn-line-hover); }}
  .social:active {{ background:var(--btn-fill-press); }}
  .social svg {{ width:18px; height:18px; flex:none; }}
  .or {{ display:flex; align-items:center; gap:.7rem; margin:.9rem 0 1rem;
        color:var(--muted); font-size:.75rem; text-transform:uppercase; letter-spacing:.06em; }}
  .or:before, .or:after {{ content:""; flex:1; border-top:1px solid var(--line); }}
  .terms {{ margin:.2rem 0 0; color:var(--muted); font-size:.75rem; text-align:center; }}
  .terms a {{ color:var(--accent); }}
  .foot a {{ color:var(--accent); text-decoration:none; }}
  .foot a:hover {{ text-decoration:underline; }}
  .ok {{ background:color-mix(in srgb,var(--accent) 10%,transparent);
        border:1px solid color-mix(in srgb,var(--accent) 40%,transparent);
        border-radius:6px; padding:.55rem .7rem; margin-bottom:1rem; font-size:.88rem; }}
  .who {{ margin:0 0 1rem; color:var(--muted); font-size:.88rem; overflow-wrap:anywhere; }}
  .who b {{ color:var(--text); font-weight:600; }}
  h2 {{ font-size:1rem; margin:1.6rem 0 .6rem; }}
  h2:first-child {{ margin-top:0; }}
  p {{ margin:.4rem 0 .8rem; }}
  .muted {{ color:var(--muted); font-size:.88rem; }}
  .panel {{ background:var(--panel); border:1px solid var(--line); border-radius:10px;
           padding:1.25rem 1.5rem; margin-bottom:1rem; }}
  form.inline {{ display:inline; background:none; border:0; padding:0; }}
  form.inline button[type=submit], a.button {{ display:inline-flex; align-items:center;
    justify-content:center; width:auto; min-height:32px; padding:0 12px; font-size:13.5px;
    border-radius:8px; border:1px solid transparent;
    background:var(--btn); color:var(--btn-text); font-weight:600; text-decoration:none;
    }}
  a.button:hover {{ background:var(--btn-hover); }}
  a.button:active {{ background:var(--btn-press); }}
  /* quiet: a small outline in muted text (Sign out, Revoke, Leave workspace) */
  button.quiet, form.inline button.quiet[type=submit] {{ min-height:32px; padding:0 12px;
    font-size:13.5px; font-weight:600; border-radius:8px; background:transparent;
    color:var(--muted); border:1px solid var(--btn-line); cursor:pointer; }}
  button.quiet:hover, form.inline button.quiet[type=submit]:hover {{ color:var(--text);
    background:var(--btn-fill-hover); border-color:var(--btn-line-hover); }}
  button.quiet:active, form.inline button.quiet[type=submit]:active {{
    background:var(--btn-fill-press); }}
  form.row {{ display:flex; gap:.5rem; align-items:flex-end; background:none; border:0;
             padding:0; margin:0 0 .5rem; }}
  form.row input {{ margin-bottom:0; }}
  form.row button[type=submit] {{ width:auto; padding:0 18px; white-space:nowrap; }}
  table {{ width:100%; border-collapse:collapse; font-size:.88rem; }}
  th, td {{ text-align:left; padding:.45rem .3rem; border-bottom:1px solid var(--line);
           vertical-align:middle; }}
  th {{ color:var(--muted); font-weight:500; font-size:.78rem; text-transform:uppercase;
       letter-spacing:.05em; }}
  pre {{ background:var(--field); border:1px solid var(--line); border-radius:6px;
        padding:.7rem .8rem; overflow-x:auto; font-size:.8rem; line-height:1.45;
        white-space:pre; margin:.4rem 0 1rem; }}
  code {{ font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }}
  ol.steps {{ padding-left:1.2rem; }} ol.steps li {{ margin:.35rem 0 .6rem; }}
  pre code.agent-prompt {{ white-space:pre-wrap; }}
  button.copy {{ min-height:32px; padding:0 12px; font-size:13.5px; font-weight:600;
                border-radius:8px; border:1px solid transparent; background:var(--btn);
                color:var(--btn-text);
                cursor:pointer; margin-bottom:.6rem; }}
  button.copy:hover {{ background:var(--btn-hover); }}
  button.copy:active {{ background:var(--btn-press); }}
  label .opt {{ text-transform:none; letter-spacing:0; font-weight:400; }}
  /* danger: an outline at rest, solid red once the pointer is on it */
  button.danger {{ background:var(--panel); color:var(--bad-text);
                  border:1px solid var(--bad-line); }}
  button.danger:hover {{ background:var(--bad-solid); border-color:var(--bad-solid); color:var(--bad-solid-text); }}
  button.danger:active {{ background:var(--bad-press); border-color:var(--bad-press); color:var(--bad-solid-text); }}
  #delete ul {{ padding-left:1.1rem; margin:.4rem 0 .8rem; font-size:.88rem; }}
  a.cta {{ display:inline-flex; align-items:center; min-height:44px; padding:0 20px;
          border-radius:8px; font-weight:600; font-size:15px; background:var(--btn);
          color:var(--btn-text); text-decoration:none; }}
  a.cta:hover {{ background:var(--btn-hover); }}
  a.cta:active {{ background:var(--btn-press); }}
  details {{ margin-top:1rem; border-top:1px solid var(--line); padding-top:.8rem; }}
  summary {{ cursor:pointer; color:var(--muted); font-size:.88rem; }}
  details[open] summary {{ margin-bottom:.6rem; }}
  label.check {{ display:flex; gap:.5rem; align-items:flex-start; text-transform:none;
                letter-spacing:0; font-size:.85rem; color:var(--muted); margin-bottom:1rem; }}
  label.check input {{ width:auto; min-height:0; margin:.2rem 0 0; }}
  __SETTINGS_CSS__
</style>
</head>
<body>
  <div class="card">
    <div class="top">
      
      <div>
        __WORDMARK__
        <span>see what your agents know</span>
      </div>
      <span class="sp"></span>
    </div>
    {form}
    <div class="foot">{foot}</div>
  </div>
</body>
</html>
"""


def _literal(text: str) -> str:
    """Text inserted into PAGE before .format() must have its braces doubled."""
    return text.replace("{", "{{").replace("}", "}}")


# The theme picker's styles. Only the settings page uses them, but they are
# small and every page shares one stylesheet.
SETTINGS_CSS = WS_MENU_CSS + AI_CSS + """
  .modes { display:inline-flex; border:1px solid var(--line); border-radius:8px;
           overflow:hidden; margin:0 0 1rem; }
  .modes label { margin:0; padding:.45rem .9rem; font-size:.85rem; letter-spacing:0;
                 text-transform:none; color:var(--text); cursor:pointer;
                 border-left:1px solid var(--line); }
  .modes label:first-child { border-left:0; }
  .modes input, .themes input { position:absolute; opacity:0; width:1px; height:1px;
                                margin:0; min-height:0; pointer-events:none; }
  .modes label:has(input:checked) { background:var(--accent); color:var(--panel); }
  .modes label:has(input:focus-visible), .themes label:has(input:focus-visible) {
    box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 35%,transparent); }
  /* three across in the 640px settings column, two on a phone */
  .themes { display:grid; grid-template-columns:repeat(3,minmax(0,1fr));
            gap:.6rem; margin:0; }
  @media (max-width:480px) { .themes { grid-template-columns:repeat(2,minmax(0,1fr)); } }
  .themes label { margin:0; padding:0; text-transform:none; letter-spacing:0;
                  font-size:.85rem; color:var(--text); cursor:pointer;
                  border:1px solid var(--line); border-radius:8px; overflow:hidden;
                  background:var(--panel); position:relative; }
  .themes label:hover { border-color:var(--accent); }
  .themes label:has(input:checked) { border-color:var(--accent);
    box-shadow:0 0 0 2px var(--accent); }
  .sw { display:block; }
  .sw .bar { display:flex; align-items:center; gap:5px; height:26px; padding:0 9px;
             background:var(--sw-l); }
  .sw .bar i { display:block; width:34px; height:5px; border-radius:3px;
               background:var(--st-l); opacity:.9; }
  .sw .bar b { display:block; width:7px; height:7px; border-radius:50%;
               background:var(--sn-l); }
  .sw .body { display:block; padding:7px 9px 0; }
  .sw .body i { display:block; height:4px; border-radius:2px; margin-bottom:4px;
                background:var(--line); }
  .sw .body i.a { width:55%; background:var(--sa-l); }
  html[data-mode="dark"] .sw .bar { background:var(--sw-d); }
  html[data-mode="dark"] .sw .bar i { background:var(--st-d); }
  html[data-mode="dark"] .sw .bar b { background:var(--sn-d); }
  html[data-mode="dark"] .sw .body i.a { background:var(--sa-d); }
  .themes .name { display:flex; justify-content:space-between; align-items:center;
                  padding:.25rem .6rem .45rem; font-weight:600; }
  .themes .name .tick { visibility:hidden; color:var(--accent); }
  .themes label:has(input:checked) .tick { visibility:visible; }
  .saved { color:var(--muted); font-size:.8rem; min-height:1.2em; margin:.6rem 0 0; }
  form.plain { background:none; border:0; padding:0; }
  fieldset.bare { border:0; margin:0 0 .4rem; padding:0; min-width:0; }
  fieldset.bare legend { font-size:.78rem; text-transform:uppercase; letter-spacing:.06em;
                         color:var(--muted); margin:0 0 .45rem; padding:0; }

  /* Settings: a sidebar of sections beside one section's panels */
  body:has(.settings) { place-items:start center; }
  .settings { display:grid; grid-template-columns:184px minmax(0,1fr); gap:2.25rem;
              align-items:start; }
  .snav { position:sticky; top:24px; display:flex; flex-direction:column; gap:2px;
          font-size:.9rem; }
  .snav .back { color:var(--muted); text-decoration:none; font-size:.85rem;
                margin:0 0 1.1rem .6rem; }
  .snav .back:hover { color:var(--text); }
  .snav .sgroup { font-size:.72rem; text-transform:uppercase; letter-spacing:.06em;
                  color:var(--muted); margin:1.1rem 0 .3rem .6rem; }
  .snav .back + .sgroup { margin-top:0; }
  /* the workspace menu (render.WS_MENU_CSS) as a full-width button on the page */
  .snav .wsm { margin:0 0 .45rem; }
  .snav .wsm-button { width:100%; height:42px; padding:0 10px 0 8px; border-color:var(--line);
    background:var(--panel); color:var(--text); font-size:.92rem; }
  .snav .wsm-button:hover, .snav .wsm-button[aria-expanded="true"] { border-color:var(--accent); }
  .snav .wsm-button .sw-chev { margin-left:auto; }
  .snav .wsm-menu { min-width:100%; width:max-content; }
  .snav a.sec { display:block; padding:.42rem .6rem; border-radius:6px; color:var(--text);
                text-decoration:none; }
  .snav a.sec:hover { background:color-mix(in srgb,var(--text) 6%,transparent); }
  .snav a.sec[aria-current="page"] { font-weight:600;
    background:color-mix(in srgb,var(--accent) 14%,transparent); }
  .sbody { min-width:0; }
  .sbody h1 { font-size:1.4rem; font-weight:650; letter-spacing:-.015em; margin:.1rem 0 1rem; }
  .sbody .panel h2 { margin-top:0; }
  .sbody a:not(.button):not(.cta) { color:var(--accent); text-decoration:none; }
  .sbody a:not(.button):not(.cta):hover { text-decoration:underline; }
  .phead { display:flex; align-items:center; justify-content:space-between; gap:1rem;
           margin:0 0 .6rem; }
  .phead h2 { margin:0; }
  /* settings form buttons are 38px; one beside a 44px input matches it */
  .sbody form.plain button[type=submit] { width:auto; min-height:38px; padding:0 16px;
    font-size:14.5px; }
  .sbody form.row button[type=submit] { min-height:44px; padding:0 18px; }
  .sbody form.row { margin-bottom:.6rem; }
  .pair { display:grid; grid-template-columns:1fr 1fr; gap:.6rem; }
  .tbl { overflow-x:auto; margin:0 0 .6rem; }
  td .sub { display:block; color:var(--muted); font-size:.8rem; overflow-wrap:anywhere; }
  .nw { white-space:nowrap; }
  .show-sm, td .sub.show-sm { display:none; }
  .tag { font-size:.72rem; color:var(--muted); border:1px solid var(--line);
         border-radius:999px; padding:0 .45rem; margin-left:.3rem; white-space:nowrap; }
  /* ⋯ row menus (details/summary, so they open without script) */
  details.menu { position:relative; display:inline-block; margin:0; padding:0; border:0; }
  details.menu > summary { list-style:none; display:inline-flex; align-items:center;
    justify-content:center; width:32px; height:32px; border:1px solid transparent;
    border-radius:6px; color:var(--muted); font-size:1.15rem; line-height:1; cursor:pointer;
    user-select:none; }
  details.menu > summary::-webkit-details-marker { display:none; }
  details.menu > summary:hover, details.menu[open] > summary { color:var(--text);
    border-color:var(--line); background:color-mix(in srgb,var(--text) 6%,transparent); }
  details.menu[open] > summary { margin-bottom:0; }
  details.menu > summary:focus-visible { outline:none;
    box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 35%,transparent); }
  /* opens to the left of its button, so it never covers the next row's button */
  .menu-list { position:absolute; right:calc(100% + 6px); top:-4px; z-index:20; min-width:200px;
    padding:4px; background:var(--panel); border:1px solid var(--line); border-radius:8px;
    box-shadow:0 8px 24px rgba(0,0,0,.18); text-align:left; }
  .menu-list form { margin:0; padding:0; border:0; border-radius:0; background:none; }
  .menu-list button[type=submit] { display:block; width:100%; min-height:34px; padding:0 .7rem;
    border:0; border-radius:5px; background:none; color:var(--text); font-size:.88rem;
    font-weight:500; text-align:left; white-space:nowrap; cursor:pointer; }
  .menu-list button[type=submit]:hover, .menu-list button[type=submit]:focus-visible {
    outline:none; background:color-mix(in srgb,var(--text) 7%,transparent); }
  .menu-list button.bad { color:var(--bad-text); }
  .menu-list button.bad:hover, .menu-list button.bad:focus-visible { background:var(--bad-bg); }
  /* .sbody's link colour and hover underline would otherwise win */
  .sbody .menu-list a.item { display:block; min-height:34px; line-height:34px; padding:0 .7rem;
    border-radius:5px; color:var(--text); font-size:.88rem; font-weight:500;
    text-decoration:none; white-space:nowrap; }
  .sbody .menu-list a.item:hover, .sbody .menu-list a.item:focus-visible {
    outline:none; text-decoration:none; background:color-mix(in srgb,var(--text) 7%,transparent); }
  /* a wiki's ⋯ menu holds its download link, then its rename form */
  .menu-list form.rename { width:260px; padding:.55rem .55rem .5rem; }
  .menu-list a.item + form.rename { border-top:1px solid var(--line); margin-top:.15rem; }
  .menu-list form.rename input[name=name] { margin:0 0 .5rem; min-height:38px;
    padding:.4rem .55rem; }
  .menu-list form.rename button[type=submit] { width:auto; min-height:32px; padding:0 12px;
    border-radius:8px; background:var(--btn); color:var(--btn-text); font-weight:600;
    text-align:center; }
  .menu-list form.rename button[type=submit]:hover { background:var(--btn-hover); }
  .menu-list form.rename button[type=submit]:active { background:var(--btn-press); }
  /* and, for an owner, its delete form under it */
  .menu-list form.del { width:260px; padding:.6rem .55rem .5rem; border-top:1px solid var(--line);
    margin-top:.15rem; }
  .menu-list form.del input[name=confirm_name] { margin:0 0 .45rem; min-height:38px;
    padding:.4rem .55rem; }
  .menu-list form.del p { margin:0 0 .55rem; font-size:.78rem; line-height:1.4;
    color:var(--muted); white-space:normal; }
  .menu-list form.del button[type=submit] { width:auto; min-height:32px; padding:0 12px;
    border-radius:8px; background:var(--panel); color:var(--bad-text);
    border:1px solid var(--bad-line);
    font-weight:600; text-align:center; }
  .menu-list form.del button[type=submit]:hover { background:var(--bad-solid);
    border-color:var(--bad-solid); color:var(--bad-solid-text); }
  .menu-list form.del button[type=submit]:active { background:var(--bad-press);
    border-color:var(--bad-press); color:var(--bad-solid-text); }
  .tbl:has(details.menu) { overflow:visible; }
  /* Previous / Next under a paged table */
  .pager { display:flex; align-items:center; gap:.5rem; margin:.2rem 0 0; font-size:.88rem; }
  .pager .muted { margin-right:auto; }
  .pager .pg { display:inline-flex; align-items:center; min-height:32px; padding:0 .75rem;
    border:1px solid var(--btn-line); border-radius:8px; font-weight:600; white-space:nowrap; }
  .sbody .pager a.pg { color:var(--text); text-decoration:none; }
  .sbody .pager a.pg:hover { background:var(--btn-fill-hover); border-color:var(--btn-line-hover);
    text-decoration:none; }
  .sbody .pager a.pg:active { background:var(--btn-fill-press); }
  .sbody .pager a.pg:focus-visible { outline:2px solid var(--accent); outline-offset:2px; }
  .pager .pg.off { color:var(--muted); opacity:.5; }
  td a.path { overflow-wrap:anywhere; }
  /* Sharing: what a share reaches, with its kind's icon (pages._target) */
  .target { display:flex; align-items:flex-start; gap:.55rem; min-width:0; }
  .target .ticon { display:flex; flex:none; margin-top:.15rem; color:var(--muted); }
  .target .ticon svg { width:16px; height:16px; fill:none; stroke:currentColor;
    stroke-width:1.4; stroke-linejoin:round; stroke-linecap:round; }
  .target .tname { min-width:0; overflow-wrap:anywhere; }
  /* Shared with people: a row naming the person, then what they can view */
  tr.who-row td { padding-top:.85rem; padding-bottom:.1rem; border-bottom:0; font-weight:600;
    overflow-wrap:anywhere; }
  tr.who-row td .sub { font-weight:400; }
  tr.item td:first-child { padding-left:1rem; }
  .acts { display:flex; flex-wrap:wrap; gap:.35rem; justify-content:flex-end; }
  .acts button { white-space:nowrap; }
  .sbody label b { text-transform:none; letter-spacing:0; color:var(--text); }
  input[type=file] { padding:.45rem .5rem; color:var(--muted); font-size:.85rem; }
  input[type=file]::file-selector-button { margin-right:.6rem; padding:.3rem .7rem;
    border:1px solid var(--line); border-radius:6px; background:var(--panel);
    color:var(--text); font:inherit; font-weight:600; cursor:pointer; }
  /* Agents: the connect panel (pages._connect_panel), on the page and always open since 2026-09-27 */
  /* its AI tiles are ais.CSS, shared with the graph screen's empty-wiki steps */
  #connect .ai-grid { margin:.4rem 0 1rem; }
  #connect h3 { font-size:.98rem; margin:1rem 0 .3rem; }
  #connect pre code.agent-prompt { overflow-wrap:anywhere; }
  button.cta { display:inline-flex; align-items:center; min-height:44px; padding:0 20px;
    border:1px solid transparent; border-radius:8px; font:inherit; font-weight:600;
    font-size:15px; background:var(--btn); color:var(--btn-text); cursor:pointer; }
  button.cta:hover { background:var(--btn-hover); }
  button.cta:active { background:var(--btn-press); }
  .cerr { color:var(--bad-text); font-size:.88rem; }
  /* Plan: what the workspace is on and costs, then every plan side by side */
  .sbody form.inline button.alt[type=submit], .sbody a.button.alt { background:none;
    color:var(--text); border:1px solid var(--btn-line); }
  .sbody form.inline button.alt[type=submit]:hover, .sbody a.button.alt:hover {
    background:var(--btn-fill-hover); border-color:var(--btn-line-hover); }
  .sbody form.inline button.alt[type=submit]:active, .sbody a.button.alt:active {
    background:var(--btn-fill-press); }
  .alert { display:flex; align-items:center; justify-content:space-between; gap:1rem;
           padding:.8rem 1rem; margin:0 0 1rem; border-radius:10px; font-size:.9rem;
           background:color-mix(in srgb,var(--accent) 9%,var(--panel));
           border:1px solid color-mix(in srgb,var(--accent) 40%,transparent); }
  .alert b { font-weight:600; }
  .alert.bad { background:var(--bad-bg); border-color:var(--bad-line); color:var(--bad-text); }
  .alert form.inline { flex:none; }
  .pill { display:inline-block; font-size:.74rem; font-weight:600; line-height:1.5;
          border-radius:999px; padding:.05rem .6rem; white-space:nowrap; color:var(--muted);
          border:1px solid var(--line); }
  .pill.ok { color:var(--good-text); border-color:var(--good-line); background:var(--good-bg); }
  .pill.warn { color:var(--warn-text); border-color:var(--warn-line); background:var(--warn-bg); }
  .pill.bad { color:var(--bad-text); border-color:var(--bad-line); background:var(--bad-bg); }
  .plan-now .phead h2 { font-size:1.15rem; }
  .price-now { font-size:.95rem; color:var(--muted); margin:.1rem 0 .1rem; }
  .price-now b { font-size:2rem; font-weight:650; letter-spacing:-.02em; color:var(--text);
                 margin-right:.15rem; }
  .plan-now > p.muted { margin-top:0; }
  dl.facts { display:grid; grid-template-columns:repeat(auto-fit,minmax(140px,1fr)); gap:.6rem;
             margin:.9rem 0 1rem; padding:.8rem 0 0; border-top:1px solid var(--line); }
  dl.facts dt { font-size:.72rem; text-transform:uppercase; letter-spacing:.06em;
                color:var(--muted); }
  dl.facts dd { margin:.1rem 0 0; font-weight:600; font-size:.92rem; }
  .plan-acts { display:flex; align-items:center; gap:.8rem; flex-wrap:wrap; }
  .plan-acts .muted { font-size:.84rem; }
  .pcards { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:.75rem;
            margin:.2rem 0 .8rem; }
  .pcard { display:flex; flex-direction:column; border:1px solid var(--line);
           border-radius:10px; padding:1rem; background:var(--panel); }
  .pcard.here { border-color:var(--accent);
                box-shadow:0 0 0 1px var(--accent) inset; }
  .pc-top { display:flex; align-items:center; justify-content:space-between; gap:.5rem; }
  .pc-top h3 { margin:0; font-size:1rem; }
  .pc-price { color:var(--muted); font-size:.82rem; margin:.35rem 0 .6rem; min-height:2.4em; }
  .pc-price b { font-size:1.35rem; font-weight:650; color:var(--text); letter-spacing:-.01em; }
  .pcard ul { margin:0 0 .9rem; padding:0; list-style:none; font-size:.85rem; flex:1; }
  .pcard li { position:relative; padding-left:1.1rem; margin:.3rem 0; }
  .pcard li:before { content:"\\2713"; position:absolute; left:0; color:var(--accent);
                     font-weight:700; }
  .pc-cta form.inline { display:block; }
  .pc-cta form.inline button[type=submit], .pc-cta a.button { width:100%;
    justify-content:center; min-height:38px; font-size:14px; }
  .pc-cta p.muted { font-size:.78rem; margin:0 0 .5rem; }
  /* Plan: the contact form's dialog; the form inside is the card */
  dialog.cdlg { width:min(540px,calc(100vw - 24px)); max-height:calc(100dvh - 24px);
    padding:0; border:0; background:none; color:var(--text); overflow:visible; }
  dialog.cdlg::backdrop { background:rgba(13,17,23,.5); }
  dialog.cdlg[open] { animation:cdin .15s ease-out; }
  @keyframes cdin { from { opacity:0; transform:translateY(6px); } }
  @media (prefers-reduced-motion:reduce) { dialog.cdlg[open] { animation:none; } }
  .cform { box-shadow:0 24px 64px -20px rgba(0,0,0,.45); }
  .cform .phead { margin-bottom:.2rem; }
  .cform .phead h2 { margin:0; font-size:1.15rem; }
  .cform .cx { width:32px; height:32px; border:0; border-radius:6px; background:none;
    color:var(--muted); font-size:1.4rem; line-height:1; cursor:pointer; }
  .cform .cx:hover { background:var(--field); color:var(--text); }
  .cform p.muted { margin:.2rem 0 1rem; overflow-wrap:anywhere; }
  .cform p.muted b { color:var(--text); font-weight:600; }
  .cform textarea, .hform textarea { width:100%; min-height:140px; padding:.65rem .7rem;
    margin-bottom:1rem;
    background:var(--field); color:var(--text); border:1px solid var(--line); border-radius:6px;
    font:inherit; font-size:16px; line-height:1.5; resize:vertical; }
  .cform textarea:focus, .hform textarea:focus { outline:none; border-color:var(--accent);
    box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 22%,transparent); }
  @media (max-width:720px) {
    .settings { grid-template-columns:minmax(0,1fr); gap:1.25rem; }
    .pcards { grid-template-columns:minmax(0,1fr); }
    .pc-price { min-height:0; }
    .alert { flex-direction:column; align-items:flex-start; }
    .snav { position:static; flex-direction:row; flex-wrap:wrap; gap:.4rem; }
    .snav .back { flex-basis:100%; margin:0 0 .2rem; }
    .snav .sgroup { flex-basis:100%; margin:.5rem 0 0; }
    .snav .wsm { flex-basis:100%; }
    .snav a.sec { border:1px solid var(--line); border-radius:999px; padding:.3rem .75rem;
                  font-size:.85rem; }
    .snav a.sec[aria-current="page"] { border-color:var(--accent); }
    .hide-sm { display:none; }
    td .sub.show-sm { display:block; }
    .acts { flex-direction:column; align-items:flex-end; }
    .sbody form.row { flex-wrap:wrap; }
    .sbody form.row > div { flex:1 1 100%; }
    .pair { grid-template-columns:minmax(0,1fr); gap:0; }
    .sbody .panel { padding:1rem; }
  }
"""

PAGE = (PAGE.replace("__WORDMARK__", f'<div class="logo">{logo(26)}</div>')
        .replace("__THEME_HEAD__", _literal(themes.head_script()))
        .replace("__THEME_CSS__", _literal(themes.css()))
        .replace("__SETTINGS_CSS__", _literal(SETTINGS_CSS)))
