"""Postgres behind the sqlite3 connection interface the server is written against.

The server's SQL is SQLite SQL, and so is every query added since. Rather than
fork it, `connect()` returns an object that behaves like the `sqlite3.Connection`
the code expects, and translates the few things Postgres spells differently:

- `?` placeholders become `%s`; a literal `%` is doubled when parameters are sent.
- `LIKE` becomes `ILIKE`: SQLite's LIKE ignores case, Postgres's does not.
- `INSERT OR IGNORE` becomes `ON CONFLICT DO NOTHING`; `INSERT OR REPLACE` becomes an
  upsert on the table's primary key.
- DDL: `INTEGER PRIMARY KEY` becomes an identity column, `INTEGER` BIGINT, `REAL`
  DOUBLE PRECISION, `TEXT` uses the "C" collation (SQLite's byte order), and
  `COLLATE NOCASE` is dropped (callers lowercase what they compare, see auth).
- `cursor.lastrowid` works for tables with an `id` identity column (the INSERT gets
  `RETURNING id`); `PRAGMA table_info` is answered from information_schema; other
  PRAGMAs are no-ops.
- Rows support `row[0]`, `row["col"]`, `dict(row)` and unpacking, like sqlite3.Row.
  NUMERIC results (SUM) come back as int or float, bool parameters go in as 0/1.
- Constraint violations raise `sqlite3.IntegrityError`, so existing handlers work.
  Inside a transaction each INSERT or UPDATE runs in a savepoint, so a caught
  violation leaves the transaction usable, as it does in SQLite (device login
  retries a colliding code this way).

Transactions follow `with conn:` as sqlite3 does: the block commits on success and
rolls back on an exception. Outside a block every statement autocommits. A block
holds one pooled connection for its thread; statements outside one borrow a
connection for that statement only, and their rows are fetched before it goes back.
"""
from __future__ import annotations

import re
import sqlite3
import threading
from decimal import Decimal

import psycopg
from psycopg_pool import ConnectionPool

_INSERT_OR = re.compile(r"^\s*INSERT\s+OR\s+(IGNORE|REPLACE)\s+INTO\s+(\w+)", re.I)
_INSERT_INTO = re.compile(r"^\s*INSERT\s+INTO\s+(\w+)\s*\(([^)]*)\)", re.I)
_PRAGMA = re.compile(r"^\s*PRAGMA\s+(\w+)\s*(?:\(\s*(\w+)\s*\))?", re.I)
_DDL = re.compile(r"^\s*(CREATE\s+TABLE|ALTER\s+TABLE)", re.I)
_CREATE_TABLE = re.compile(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\((.*?)\)\s*;",
                           re.I | re.S)


class Row(tuple):
    """A result row that answers to position and to column name, like sqlite3.Row."""

    def __new__(cls, names: tuple, values):
        row = super().__new__(cls, values)
        row._names = names
        return row

    def keys(self):
        return list(self._names)

    def __getitem__(self, i):
        if isinstance(i, str):
            try:
                return tuple.__getitem__(self, self._names.index(i))
            except ValueError:
                raise IndexError(f"no such column: {i}") from None
        return tuple.__getitem__(self, i)


class Cursor:
    """Rows already fetched, so the connection could go back to the pool."""

    def __init__(self, rows: list, rowcount: int = -1, lastrowid=None):
        self._rows, self._i = rows, 0
        self.rowcount, self.lastrowid = rowcount, lastrowid

    def fetchone(self):
        if self._i >= len(self._rows):
            return None
        self._i += 1
        return self._rows[self._i - 1]

    def fetchall(self):
        rest, self._i = self._rows[self._i:], len(self._rows)
        return rest

    def __iter__(self):
        return iter(self.fetchall())


def _plain(v):
    if isinstance(v, Decimal):
        return int(v) if v == v.to_integral_value() else float(v)
    return v


def _param(v):
    return int(v) if isinstance(v, bool) else v


def _swap_outside_quotes(sql: str, fn) -> str:
    """Apply fn to each stretch of sql that is not inside single quotes."""
    out, i = [], 0
    for m in re.finditer(r"'(?:[^']|'')*'", sql):
        out.append(fn(sql[i:m.start()]))
        out.append(m.group(0))
        i = m.end()
    out.append(fn(sql[i:]))
    return "".join(out)


def translate_ddl(sql: str) -> str:
    # Type names only: the schemas write types in capitals and column names in
    # lower case, and `text` is also a column name, so matching is case-sensitive.
    def fix(s: str) -> str:
        s = re.sub(r"\bINTEGER PRIMARY KEY\b",
                   "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", s)
        s = re.sub(r"\bINTEGER\b", "BIGINT", s)
        s = re.sub(r"\bREAL\b", "DOUBLE PRECISION", s)
        s = re.sub(r"\s+COLLATE NOCASE\b", "", s)
        return re.sub(r"\bTEXT\b", 'TEXT COLLATE "C"', s)
    # Comments may hold apostrophes, which would throw the quote tracking off.
    sql = re.sub(r"--[^\n]*", "", sql)
    return _swap_outside_quotes(sql, fix)


class PgConnection:
    def __init__(self, url: str, max_size: int = 10):
        self.url = url
        self.pool = ConnectionPool(url, min_size=1, max_size=max_size, open=True,
                                   kwargs={"autocommit": True})
        self._local = threading.local()
        self._meta_lock = threading.Lock()
        self._pk: dict[str, list[str]] = {}
        self._has_id: set[str] = set()
        self.row_factory = None  # accepted and ignored, as with sqlite3
        with self.pool.connection() as c:
            self._load_tables(c)

    # ---- sqlite3.Connection interface ----------------------------------
    def execute(self, sql: str, params=()) -> Cursor:
        held = getattr(self._local, "conn", None)
        if held is not None:
            return self._run(held, sql, params)
        try:
            with self.pool.connection() as c:
                return self._run(c, sql, params)
        except psycopg.OperationalError:
            # A pooled connection the server dropped (a restart, a failover) fails
            # on first use and the pool discards it. Outside a transaction the
            # statement is safe to send once more, on a fresh connection.
            with self.pool.connection() as c:
                return self._run(c, sql, params)

    def executemany(self, sql: str, seq) -> Cursor:
        seq = [tuple(_param(v) for v in p) for p in seq]
        if not seq:
            return Cursor([], 0)
        q = self._translate(sql, True)
        held = getattr(self._local, "conn", None)
        try:
            if held is not None:
                cur = held.cursor()
                cur.executemany(q, seq)
                return Cursor([], cur.rowcount)
            with self.pool.connection() as c, c.transaction():
                cur = c.cursor()
                cur.executemany(q, seq)
                return Cursor([], cur.rowcount)
        except psycopg.IntegrityError as e:
            raise sqlite3.IntegrityError(str(e)) from e

    def executescript(self, script: str) -> Cursor:
        script = translate_ddl(script)
        held = getattr(self._local, "conn", None)
        if held is not None:
            held.execute(script)
            self._load_tables(held)
        else:
            with self.pool.connection() as c:
                c.execute(script)
                self._load_tables(c)
        return Cursor([], -1)

    def commit(self) -> None:
        """Statements outside `with conn:` have already committed."""

    def rollback(self) -> None:
        """Only a `with conn:` block has anything to roll back, and it does so itself."""

    def close(self) -> None:
        self.pool.close()

    def __enter__(self):
        depth = getattr(self._local, "depth", 0)
        if depth == 0:
            self._local.lease = self.pool.connection()
            self._local.conn = self._local.lease.__enter__()
            self._local.txs = []
        tx = self._local.conn.transaction()
        tx.__enter__()
        self._local.txs.append(tx)
        self._local.depth = depth + 1
        return self

    def __exit__(self, et, ev, tb):
        tx = self._local.txs.pop()
        self._local.depth -= 1
        try:
            tx.__exit__(et, ev, tb)
        except psycopg.IntegrityError as e:  # raised by the COMMIT itself
            raise sqlite3.IntegrityError(str(e)) from e
        finally:
            if self._local.depth == 0:
                lease, self._local.conn, self._local.lease = self._local.lease, None, None
                lease.__exit__(None, None, None)
        return False

    # ---- translation ---------------------------------------------------
    def _load_tables(self, c) -> None:
        """Primary keys and identity `id` columns, for OR REPLACE and lastrowid."""
        rows = c.execute(
            "SELECT tc.table_name, kcu.column_name FROM information_schema.table_constraints tc"
            " JOIN information_schema.key_column_usage kcu"
            " ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema"
            " WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = current_schema()"
            " ORDER BY kcu.ordinal_position").fetchall()
        ids = c.execute(
            "SELECT table_name FROM information_schema.columns WHERE table_schema ="
            " current_schema() AND column_name = 'id' AND is_identity = 'YES'").fetchall()
        pk: dict[str, list[str]] = {}
        for table, col in rows:
            pk.setdefault(table, []).append(col)
        with self._meta_lock:
            self._pk, self._has_id = pk, {r[0] for r in ids}

    def _translate(self, sql: str, has_params: bool) -> str:
        m = _INSERT_OR.match(sql)
        if m:
            verb, table = m.group(1).upper(), m.group(2)
            sql = _INSERT_OR.sub(f"INSERT INTO {table}", sql, count=1).rstrip().rstrip(";")
            if verb == "IGNORE":
                sql += " ON CONFLICT DO NOTHING"
            else:
                cols = _INSERT_INTO.match(sql)
                keys = self._pk.get(table.lower()) or []
                if not cols or not keys:
                    raise sqlite3.OperationalError(f"INSERT OR REPLACE needs a primary key on {table}")
                names = [c.strip() for c in cols.group(2).split(",")]
                sets = ", ".join(f"{n}=EXCLUDED.{n}" for n in names if n not in keys)
                sql += f" ON CONFLICT ({', '.join(keys)}) DO " + (
                    f"UPDATE SET {sets}" if sets else "NOTHING")
        if _DDL.match(sql):
            sql = translate_ddl(sql)

        def fix(s: str) -> str:
            if has_params:
                s = s.replace("%", "%%").replace("?", "%s")
            return re.sub(r"(?<![A-Za-z_])LIKE\b", "ILIKE", s, flags=re.I)
        sql = _swap_outside_quotes(sql, fix)
        if has_params:  # a % inside a quoted literal must be doubled too
            sql = re.sub(r"'(?:[^']|'')*'", lambda m: m.group(0).replace("%", "%%"), sql)
        return sql

    def _pragma(self, c, m) -> Cursor:
        if m.group(1).lower() != "table_info":
            return Cursor([], -1)
        cur = c.execute(
            "SELECT ordinal_position - 1 AS cid, column_name AS name, data_type AS type,"
            " CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,"
            " column_default AS dflt_value, 0 AS pk FROM information_schema.columns"
            " WHERE table_schema = current_schema() AND table_name = %s"
            " ORDER BY ordinal_position", (m.group(2).lower(),))
        names = tuple(d.name for d in cur.description)
        return Cursor([Row(names, r) for r in cur.fetchall()])

    def _run(self, c, sql: str, params) -> Cursor:
        m = _PRAGMA.match(sql)
        if m:
            return self._pragma(c, m)
        params = tuple(_param(v) for v in (params or ()))
        q = self._translate(sql, bool(params))
        ins = _INSERT_INTO.match(q)
        want_id = bool(ins) and ins.group(1).lower() in self._has_id \
            and not re.search(r"\bRETURNING\b", q, re.I)
        if want_id:
            q = q.rstrip().rstrip(";") + " RETURNING id"
        guard = c is getattr(self._local, "conn", None) and re.match(r"\s*(INSERT|UPDATE)\b", q, re.I)
        try:
            if guard:
                with c.transaction():  # a savepoint
                    cur = c.execute(q, params or None)
            else:
                cur = c.execute(q, params or None)
        except psycopg.IntegrityError as e:
            raise sqlite3.IntegrityError(str(e)) from e
        if _DDL.match(sql):
            self._load_tables(c)
        if cur.description is None:
            return Cursor([], cur.rowcount)
        names = tuple(d.name for d in cur.description)
        rows = [Row(names, tuple(_plain(v) for v in r)) for r in cur.fetchall()]
        if want_id:
            return Cursor([], cur.rowcount, rows[0][0] if rows else None)
        return Cursor(rows, cur.rowcount)


def is_url(target) -> bool:
    return str(target or "").startswith(("postgres://", "postgresql://"))


def connect(url: str) -> PgConnection:
    return PgConnection(url)
